### ISSUE TITLE
secret key in repo

### ISSUE THREAD

**Issue by silky** [mitchellwrosen/test-request-bin#1]
https://github.com/mitchellwrosen/test-request-bin/blob/master/email.hs#L16

**Comment by mitchellwrosen** [comment]
Heh, thanks. I've no idea what the hell this repository even _is_.

**Comment by silky** [comment]
np, i stumbled across it looking for examples of mime-mail-ses usage :)

**Comment by mitchellwrosen** [comment]
Look far, far away from here. This code looks like garbage. Again, thanks! Deleting this repo now.
